# sonar-project.properties
sonar.organization=gestion-source
sonar.projectKey=farmaciasperuanas.frontend
sonar.projectName=Farmacias Peruanas Frontend

# Directorio de código fuente y exclusiones
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/assets/**,**/environments/**

# Directorio donde están las pruebas
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Lenguaje principal
sonar.language=ts