# sonar-project.properties
sonar.organization=gestion-source
sonar.projectKey=GESTION-SOURCE_farmaciasperuanas.frontend
sonar.projectName=Farmacias Peruanas Frontend

# Directorio de código fuente y exclusiones
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/assets/**,**/environments/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.language=ts

sonar.javascript.lcov.reportPaths=coverage/farmaciasperuanas-frontend/lcov.info